services:
  postgres:
    image: postgres:18.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      LYA_DB_USERNAME: lya
      LYA_DB_PASSWORD: lya
      LYA_DB_NAME: lya
    volumes:
      - ./postgres/data:/var/lib/postgresql
      - ./postgres/docker-entrypoint-initdb.d/lya-postgres-init.sh:/docker-entrypoint-initdb.d/lya-postgres-init.sh:ro
      - ./postgres/healthcheck.sh:/usr/local/bin/healthcheck.sh:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - lya_network

  lya-api:
    depends_on:
      postgres:
        condition: service_healthy

networks:
  lya_network:
