version: '3'

includes:
  api:
    taskfile: ./api/Taskfile.yml
    dir: ./api
  ui:
    taskfile: ./ui/Taskfile.yml
    dir: ./ui

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all

  lint:
    desc: Lint both API and UI codebases
    cmds:
      - task: api:lint
      - task: ui:lint
  
  format:
    desc: Format both API and UI codebases
    cmds:
      - task: api:format
      - task: ui:format
