#!/bin/bash
set -e
export PGPASSWORD="$POSTGRES_PASSWORD";
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE "${LYA_DB_USERNAME}" WITH LOGIN PASSWORD '${LYA_DB_PASSWORD//\'/\'\'}';
    CREATE DATABASE "${LYA_DB_NAME}" OWNER "${LYA_DB_USERNAME}";
    GRANT ALL PRIVILEGES ON DATABASE "${LYA_DB_NAME}" TO "${LYA_DB_USERNAME}";
EOSQL
