version: '3'

vars:
  SERVICE_NAME: 'lya-ui'

tasks:
  shell:
    desc: Open a shell in the UI container
    cmds:
      - docker compose exec {{.SERVICE_NAME}} sh

  lint:
    desc: Lint the UI codebase
    cmds:
      - docker compose exec {{.SERVICE_NAME}} pnpm lint
  
  format:
    desc: Format the UI codebase
    cmds:
      - docker compose exec {{.SERVICE_NAME}} pnpm format
