version: '3'

vars:
  SERVICE_NAME: 'lya-api'

tasks:
  shell:
    desc: Open a shell in the API container
    cmds:
      - docker compose exec {{.SERVICE_NAME}} sh

  lint:
    desc: Lint the API codebase
    cmds:
      - docker compose exec {{.SERVICE_NAME}} pnpm lint
  
  format:
    desc: Format the API codebase
    cmds:
      - docker compose exec {{.SERVICE_NAME}} pnpm format
